### ISSUE TITLE
Bad cards number of tickets when plugin is enable

### ISSUE THREAD

**Issue by si-ademi** [InfotelGLPI/resources#104]
Hi,

* Version of the plugin : 2.7.0
* Version of your GLPI : 9.5.5

* Steps to reproduce (which actions have you made) :
Enable the plugin
Go to "Assistance" > "Create ticket"

* Expected result :
The cards display the correct number of tickets (14 tickets in our case) :
![image](https://user-images.githubusercontent.com/83706897/117139677-ccfc5080-adac-11eb-9cbb-ad50e39e66c7.png)

* Actual result :
The cards display "0" :
![image](https://user-images.githubusercontent.com/83706897/117139591-b81fbd00-adac-11eb-878d-5e1736b1979b.png)
Or sometimes another number : 
![image](https://user-images.githubusercontent.com/83706897/117140625-e6ea6300-adad-11eb-898b-4bb358c64aee.png)

The title of span is good, but not the number : 
![image](https://user-images.githubusercontent.com/83706897/117140165-63307680-adad-11eb-9670-f97d809c337b.png)

* URL of the page :
/front/ticket.php

When I disable the resources plugin, all is good. On the main dashboard (/front/central.php), all is good : 
![image](https://user-images.githubusercontent.com/83706897/117140451-b73b5b00-adad-11eb-9295-9f84837773a6.png)

Thanks for your job 👍

**Comment by tsmr** [comment]
Hello. Sorry but i think it's a cache problem from GLPI and it's not linked with the plugin. Resouces plugin doesn't intercat with glpi dashboard
