### ISSUE TITLE
Plugin bug in "declare an arrival"

### ISSUE THREAD

**Issue by FRANCOIS50** [InfotelGLPI/resources#110]
Dear GLPi user.

BEFORE SUBMITTING YOUR ISSUE, please make sure to read and follow these steps :

* Verify that your question has not already been asked
* Please use the below template.
* Delete this text before submiting your issue.

The Plugin team.

------------
* Version of the plugin : 2.7.0

* Version of your GLPI : 9.5.2

* Steps to reproduce (which actions have you made) :
- Declare an arrival
- select type of contract
- next
- First name; surname; ressource manager etc..........
- next
- employer
- Add a need --> in debug mode following message appear  --> Uncaught Exception TypeError: Argument 1 passed to Dropdown::addNewCondition() must be of the type array, string given, called in /usr/share/glpi/inc/dropdown.class.php on line 158 in /usr/share/glpi/inc/dropdown.class.php at line 280
And no filed is displayer:

![image](https://user-images.githubusercontent.com/12511115/151969122-ba1174f8-7097-4a89-a3d5-03ba17d075e0.png)

* Expected result : filed to be able to type in needs

* Actual result :

* URL of the page :

* Screenshot of the problem (if pertinent) :

Could you check this strange situation?

Thanks in advance for your help

**Comment by FRANCOIS50** [comment]
I tried with the latest GLPI version 9.5.7 and I have the same problème.
Could you please help me?
Thanks in advance

**Comment by tsmr** [comment]
Fixed by curtis (thanks to him) #111

**Comment by FRANCOIS50** [comment]
The fixe mentioned above doesn't solve the problem.

**Comment by tsmr** [comment]
Change here : https://github.com/InfotelGLPI/resources/blob/9.5/Bugfixes/inc/choice.class.php#L342

**Comment by FRANCOIS50** [comment]
Thank you for the fixe. it works now.
