### ISSUE TITLE
3.0.0 does not install on GLPI 10.0.1

### ISSUE THREAD

**Issue by maturbet-volta** [InfotelGLPI/resources#114]
------------
* Version of the plugin : 3.0.0
* Version of your GLPI : 10.0.1
* Version of your php : 8.1
* Version of your database : mariadb 10
* Version of your OS : debian bullseye

* Steps to reproduce (which actions have you made) :
First action on fresh installation of GLPI. Connexion with glpi user and install the plugin

* Actual result :
Plugins not installed with many 'Warning' in the browser.

* URL of the page : http://localhost/front/plugin.form.php

* Screenshot of the problem :

![image](https://user-images.githubusercontent.com/88138615/173532871-93de6fad-ee88-4437-95be-47026b6329f5.png)

![image](https://user-images.githubusercontent.com/88138615/173531974-5104e5f7-45fa-42da-ba91-21fd326e6608.png)

**Comment by maturbet-volta** [comment]
A second installation essay return this screen :
![image](https://user-images.githubusercontent.com/88138615/173533577-7d9c1e2b-d94c-4409-9917-d24d7e01eebb.png)

**Comment by tsmr** [comment]
Can you try with last master plz ?
https://github.com/InfotelGLPI/resources/archive/refs/heads/master.zip

**Comment by maturbet-volta** [comment]
![image](https://user-images.githubusercontent.com/88138615/174039328-c9af385a-7f28-4568-a7b9-0708f4964747.png)

**Comment by maturbet-volta** [comment]
It seems OK after commenting calls of `/vendor/autoload.php` in `setup.php` ...

**Comment by maturbet-volta** [comment]
OK in 3.0.1 !
Thanks !
