### ISSUE TITLE
Error with rank dropdown

### ISSUE THREAD

**Issue by tsmr** [InfotelGLPI/resources#12]
Un simple accès à la liste (vide) de l'intitulé Grade provoque 2 erreurs PHP et une erreur SQL.
Puis impossible de créer des grades

ci-après l'erreur sql
SQL: SELECT \'glpi\' AS currentuser,
`glpi_plugin_resources_ranks`.`entities_id`, `glpi_plugin_resources_ranks`.`is_recursive`, `glpi_plugin_resources_ranks`.`name` AS ITEM_0,
`glpi_plugin_resources_ranks`.`id` AS ITEM_0_2,
`glpi_entities`.`completename` AS ITEM_1,
`glpi_plugin_resources_ranks`.`is_recursive` AS ITEM_2,
`glpi_plugin_resources_ranks`.`Nom - court` AS ITEM_3,
`glpi_plugin_resources_ranks`.`id` AS id FROM `glpi_plugin_resources_ranks`LEFT JOIN `glpi_entities`
ON (`glpi_plugin_resources_ranks`.`entities_id` = `glpi_entities`.`id`
) WHERE ( 1 ) ORDER BY ITEM_0 ASC LIMIT 0, 50
Error: Unknown column 'glpi_plugin_resources_ranks.Nom - court' in 'field list'
Backtrace :
/var/www/glpiOLD/inc/search.class.php :790 DBmysql->query()
/var/www/glpiOLD/inc/search.class.php :63 Search::showList()
/var/www/glpiOLD/front/dropdown.common.php :51 Search::show()
/var/www/glpiOLD/plugins/resources/front/rank.php :33 include()
/var/www/glpiOLD/plugins/resources/front/rank.php

**Comment by amma35** [comment]
Fixed in the latest version
