### ISSUE TITLE
SQL error when a contract type has a translation

### ISSUE THREAD

**Issue by blerohellec** [InfotelGLPI/resources#13]
v 2.2.0 (GLPI 0.90)
Give a contract type (eg : fixed term contract) a translation to the current language, and create a HR with this contract type.
Go to search resources -> sql error (extract hereafter)
No error when contract type do not have any translation.

SQL: SELECT \'glpi\' AS currentuser,
                        `glpi_plugin_resources_resources`.`entities_id`, `glpi_plugin_resources_resources`.`is_recursive`, `glpi_plugin_resources_resources`.`name` AS META_0,`glpi_plugin_resources_resources`.`name` AS ITEM_0, `glpi_plugin_resources_resources`.`id` AS ITEM_0_2, `glpi_entities`.`completename` AS `ITEM_1`,  `glpi_plugin_resources_resources`.`firstname` AS `ITEM_2`,  `glpi_plugin_resources_contracttypes`.`name` AS `ITEM_3`, IFNULL(`glpi_plugin_resources_contracttypes_trans`.`value`,\'**NULL**\')  AS `ITEM_3_trans`,   `glpi_users`.`name` AS `ITEM_4`,
                        `glpi_users`.`realname` AS `ITEM_4_realname`,
                        `glpi_users`.`id`  AS `ITEM_4_id`,
                        `glpi_users`.`firstname` AS `ITEM_4_firstname`,
                        `glpi_plugin_resources_resources`.`date_begin` AS `ITEM_5`,  `glpi_plugin_resources_resources`.`date_end` AS `ITEM_6`,   GROUP_CONCAT(DISTINCT CONCAT(IFNULL(`glpi_plugin_resources_resources_items`.`items_id`, \'**NULL**\'),
                                               \'$#$\',`glpi_plugin_resources_resources_items`.`id`) SEPARATOR \'$$##$$\')
                              AS `ITEM_7`,

```
              `glpi_plugin_resources_resources`.`id` AS id  FROM `glpi_plugin_resources_resources`LEFT JOIN `glpi_entities` 
                                      ON (`glpi_plugin_resources_resources`.`entities_id` = `glpi_entities`.`id`
                                          ) LEFT JOIN `glpi_plugin_resources_contracttypes` ON (`glpi_plugin_resources_resources`.`plugin_resources_contracttypes_id` = `glpi_plugin_resources_contracttypes`.`id`) LEFT JOIN `glpi_users` 
                                      ON (`glpi_plugin_resources_resources`.`users_id` = `glpi_users`.`id`
                                          ) LEFT JOIN `glpi_plugin_resources_resources_items` ON (`glpi_plugin_resources_resources`.`id` = `glpi_plugin_resources_resources_items`.`items_id` AND `glpi_plugin_resources_resources_items`.`itemtype`= \'PluginResourcesResource\')  WHERE  `glpi_plugin_resources_resources`.`is_deleted` = \'0\'  AND `glpi_plugin_resources_resources`.`is_template` = \'0\'  GROUP BY `glpi_plugin_resources_resources`.`id` ORDER BY ITEM_0 ASC  LIMIT 0, 20
```

  Error: Unknown column 'glpi_plugin_resources_contracttypes_trans.value' in 'field list'
  Backtrace :
  inc/search.class.php:892  
  inc/search.class.php:98                            Search::constructDatas()
  inc/search.class.php:81                            Search::showList()
  plugins/resources/front/resource.php:79            Search::show()

**Comment by amma35** [comment]
Bug of core in progress: see https://github.com/glpi-project/glpi/issues/1112
