### ISSUE TITLE
Translate Information

### ISSUE THREAD

**Issue by rcfloresh** [InfotelGLPI/resources#17]
How I can translate to another language?... all the screens is on french... and when I try to change it with the file "tools/move_to_po.php" show the next message:

Notice: Undefined variable: argv in C:\xampp\htdocs\glpi\plugins\resources\tools\move_to_po.php on line 38
Usage move_to_po.php lang=xx_YY Will take the pot file and try to complete it to create initial po for the lang 
Notice: Undefined index: lang in C:\xampp\htdocs\glpi\plugins\resources\tools\move_to_po.php on line 58
Unable to read dictionnary file

**Comment by tsmr** [comment]
Hello. You must use transifex : 
Create account & go on https://www.transifex.com/tsmr/GLPI_resources/ for submit new language

**Comment by rcfloresh** [comment]
Download the language you need, but do not know how to install it?

**Comment by tsmr** [comment]
I don't understand.

**Comment by rcfloresh** [comment]
On the website  https://www.transifex.com/tsmr/GLPI_resources/ , I downloaded the language that I need, but not how to install, change or steps that I must perform to show the language I need.

**Comment by tsmr** [comment]
You must rename like others language & compile it with tool like poedit for have 2 files : .po & .mo

**Comment by rcfloresh** [comment]
I really appreciate the help, thank you very much, make the changes.
