### ISSUE TITLE
Human ressources some Alert are missing in massive action "link a task"

### ISSUE THREAD

**Issue by FRANCOIS50** [InfotelGLPI/resources#18]
After the massive action "link a task" for more than one check in the checklist, the alert (Mail) for the first check of the liste is sent. other alerts (mail) for the next checks will not be sent.

**Comment by amma35** [comment]
Which events are affected?

**Comment by FRANCOIS50** [comment]
Hi sorry for the very late answer but have to stop my GLPi installation to manage an other IT project. Now i can start again this installation and I can answer to your question:
the affected event is "link a Task" to assign a task to a person. The notification is "new resource tasks" activated with the event "Adding a task to a resource" thank you in advance for your help

**Comment by amma35** [comment]
Now it is not possible in the email queue to have multiple notifications of the same type, for the same object, in the same entity, for the same notification model and the same recipient. 

This is the last task that is kept in the notification queue.

A modification should be made when adding tasks via the checklist to send a notification with all tasks.

**Comment by FRANCOIS50** [comment]
I installed 2.4.2 but it seems that there is a problem with a variable in the new code --> each time when I execute a "link to a task" I didn't  receive any notification and I can see the following warning in the PHP.log file:
*** PHP Notice(8): Array to string conversion
  Backtrace :
  ...es/inc/notificationtargetresource.class.php:226 
  ...es/inc/notificationtargetresource.class.php:131 PluginResourcesNotificationTargetResource->getTaskTechAddress()
  inc/notificationtarget.class.php:1069              PluginResourcesNotificationTargetResource->addSpecificTargets()
  inc/notificationeventabstract.class.php:86         NotificationTarget->addForTarget()
  inc/notificationevent.class.php:164                NotificationEventAbstract::raise()
  plugins/resources/inc/checklist.class.php:870      NotificationEvent::raiseEvent()
  inc/massiveaction.class.php:991                    PluginResourcesChecklist::processMassiveActionsForOneItemtype()
  inc/massiveaction.class.php:970                    MassiveAction->processForSeveralItemtypes()
  front/massiveaction.php:63                         MassiveAction->process()

**Comment by amma35** [comment]
Can you test with this commit  https://github.com/InfotelGLPI/resources/commit/c1129400b96b404fbd003d448eebed789859b927 ?
