### ISSUE TITLE
Human ressouces - Wrong display

### ISSUE THREAD

**Issue by FRANCOIS50** [InfotelGLPI/resources#19]
See in the following print screen the buttons to move checks in the checklist attributed to a ressource are availlable. but there is no sence to use them in this situation.
![bc180f18-8187-11e5-9a5d-d812b14da9e2](https://cloud.githubusercontent.com/assets/12511115/11621286/a2879656-9cba-11e5-9dfb-adf678390d50.png)

**Comment by amma35** [comment]
Indeed this feature could be removed
