### ISSUE TITLE
PHP errors on task list of a resource

### ISSUE THREAD

**Issue by tsmr** [InfotelGLPI/resources#2]
2015-07-30 14:47:28 [6@P365]
  **\* PHP Notice(8): Undefined index: itemtype
  Backtrace :
  inc\search.class.php:1469  
  inc\search.class.php:1443                          Search::isDeletedSwitch()
  plugins\resources\inc\task.class.php:577           Search::displayDatas()
  plugins\resources\inc\task.class.php:237           PluginResourcesTask::showMinimalList()
  inc\commonglpi.class.php:465                       PluginResourcesTask::displayTabContentForItem()
  ajax\common.tabs.php:91                            CommonGLPI::displayStandardTab()

**Comment by amma35** [comment]
Corrected in the latest version
