### ISSUE TITLE
Add "contract type"

### ISSUE THREAD

**Issue by FranckMTP** [InfotelGLPI/resources#24]
Hi,

There is 3 contracts types by default and I need to create others, but I can't.

Even if have super-admin right, I can't click on the cross bouton to add a new contract type.

Can you help me with that ?

Franck

**Comment by amma35** [comment]
Indeed, it is not possible to add a new type of contract, it is a bug.
I correct it right problem.

**Comment by FranckMTP** [comment]
Thank you

Just a dumb question, I just need to import those 2 in the "Front" folder ?

**Comment by amma35** [comment]
This depends on whether you have the latest release (GLPI 9.1 : Version 2.3.0 disponible / available), you are replacing the two files I modified in the location where you downloaded them. 
That is, resources / front /.

On the other hand if you have another version, you will have to apply the modifications I have made yourself. (There is very little change)

**Comment by FranckMTP** [comment]
We have the lastest version of GLPI and of the plugin too.

My administrator says that maybe a file or a line in a file is missing to make your code work.

He just put the files contracttype.class.php and tasktype.class.php on the folder ressource/front and it still doesn't work.

**Comment by amma35** [comment]
Did you restart your session?

Do the other titles of the resource plugin work?

**Comment by FranckMTP** [comment]
Yes I restart it.

I find the issue now it work nicely.

I told him to put those file into the folder ressource/inc where is store all the .class.php.
