### ISSUE TITLE
Wizard problem

### ISSUE THREAD

**Issue by JulienG78** [InfotelGLPI/resources#25]
Hi,

Thank you first for this plugin ! I think it will help us.

We have problems using this plugin in version 2.3.0 with GLPI 9.1

When we clic on the wizard to declare a ressource, the first page ask us to select a contract type, the only option is "without contract", even if there are some contracts type in the contract type menu.

I don't know why in the wizard there is no contract type available.

In the contracts types I see an option "Wizard ressource creation" line, but no option available.
It might be the reason of the problem.

Any idea ?
thanks
![07-12-2016 15-24-03](https://cloud.githubusercontent.com/assets/24435635/20971321/4d4866e6-bc91-11e6-86a6-0f8cf44e9a6d.png)

**Comment by JulienG78** [comment]
I saw in the contracttype.class.php that the wizard resource creation "type" was blank. I type "bool" like the other fields.
Now in the contract type I can select YES / NO in the wizard resource creation option. But after saving the contract type and choosed YES, it stays with NO... :(

**Comment by tsmr** [comment]
For your fist question, you need to create a template with this link icon : 

![image](https://cloud.githubusercontent.com/assets/13178158/20971827/35a2e488-bc93-11e6-8ef5-11cd36f63044.png)

**Comment by JulienG78** [comment]
Thank you it works !
