### ISSUE TITLE
Profiles rights bugs

### ISSUE THREAD

**Issue by JulienG78** [InfotelGLPI/resources#26]
Hi,

I see that if I create a limited profile to be able just to watch the ressource informations and the tasks informations (like a manager profile).
The manager is able to create new ressource, and to create/manage all templates and datas...

It's amazing because in the profile rights options I only setup this :
![08-12-2016 17-22-52](https://cloud.githubusercontent.com/assets/24435635/21017924/4197dff4-bd6b-11e6-8e89-a19def804725.png)

PS : Is it possible to restrict the resources access by profile or manager that have been setup as manager of the ressource ? I'm trying to setup a manager profile to make them able to add informations to a new ressource, but I don't want them to see all the resources in the plugin.

Thank you
!

**Comment by didinem2** [comment]
If I understood correctly the problem is that the manager can handle the title such as: Types of contract, Human Resources - Statutes, Departments, Employers, Affected Customers, Types of need, Reasons for leaving ?

**Comment by amma35** [comment]
If I understood correctly the problem is that the manager can handle the title such as: Types of contract, Human Resources - Statutes, Departments, Employers, Affected Customers, Types of need, Reasons for leaving ?

**Comment by amma35** [comment]
No answers, I close.
