### ISSUE TITLE
Pas d'entrée "Plugin > Ressources humaines" depuis une nouvelle installation

### ISSUE THREAD

**Issue by rmichalowicz** [InfotelGLPI/resources#32]
Bonjour,

Je dispose actuellement de la version de GLPI suivante: 
GLPI 9.1.1  / FusionInventory 9.1+1.0

J'ai souhaité utiliser la version 2.3.1 du plugin ressources humaines. Ce dernier est installé avec succès.
Toutefois je ne vois pas le menu plugin > Ressources humaines qui me permettrait de configurer l'arrivée, le départ, la mutation etc.. Par contre les paramètres dans Configuration > Intitulés sont bien accessibles.

J'ai donc fait un test avec la version 2.3.0 du plugin et là le menu est bien présent.

Aurais-je oublié une étape dans la nouvelle version ou serait-ce un bug ?

Par avance merci pour votre aide

Bien cordialement

Richard

**Comment by tsmr** [comment]
Il a été déporté dans le Menu Administration maintenant

**Comment by rmichalowicz** [comment]
Problème résolu avec la dernière mouture. Je retrouve bien le menu "ressources humaines" dans l'onglet ressources.

Le Ticket peut être clos.

Merci encore pour votre réactivité!

Richard
