### ISSUE TITLE
Taches dans gabarit ressources humaines

### ISSUE THREAD

**Issue by imatechamabon** [InfotelGLPI/resources#37]
Bonjour,
- The version of the plugin Ressources humaines : 2.2.1
remplacement des fichiers contracttype.class.php et tasktype.class.php (issue #24)
- The version of your GLPI. : 0.90.1
- The steps to reproduce your issue.
Dans un gabarit , j'ai créé des tâches. Lorsque je créé un utilisateur à partir de ce gabarit, les tâches sont créés en double et n'apparaissent plus ensuite dans le gabarit.

Merci
Alain Mabon

**Comment by J-n-s** [comment]
Reproduce with GLPI 9.1.2 with Resources 2.3.0 (+correction issue #24). 
When creating a new resource using a template, the tasks for this new resource are duplicated.

**Comment by amma35** [comment]
Fix in [2.4.0](https://github.com/InfotelGLPI/resources/releases/tag/2.4.0)
