### ISSUE TITLE
Unable to change Field "Sales Manager" into "Resources Manager" like described in the documentation

### ISSUE THREAD

**Issue by rmichalowicz** [InfotelGLPI/resources#38]
Hi,

- The version of the plugin: 2.3.1
- The version of your GLPI: 9.1.1
- The steps to reproduce your issue :

Im in the case of public service described in the documentation of the plugin Resources ( [https://forge.glpi-project.org/attachments/1330/Guide_Utilisateur_Resource_service_public.pdf](https://forge.glpi-project.org/attachments/1330/Guide_Utilisateur_Resource_service_public.pdf) ). This document indicate in page 12 a field named Resource Manager instead of sales Manager. 

I want to change the field "sales manager" into "Resource manager" like the template in page 13 of the documentation. How can i do it with the actual version of the plugin without putting my hands in source code ?
Thanks a lot

Richard

**Comment by amma35** [comment]
Hi,
The version of the plugin 2.3.1 is under development, it should not be used, you may lose information, which is why the documentation is not up to date with this version.

The "Resource Manager" field is still present but a new field has been added which is "Sales manager".

**Comment by rmichalowicz** [comment]
Im testing the use of Human Resources plugin it's not in production yet. I hope soon :)
Is it possible to hide the field sales managers in my template ?

**Comment by rmichalowicz** [comment]
=> Is it possible to hide the field sales managers in my template ?

**Comment by amma35** [comment]
For the moment, it is not possible to hide the field sales managers.
A fee may be added later.

**Comment by amma35** [comment]
I close for the moment because to hide fields it would be necessary to add a rule engine as well as mandatory fields.
This is a new feature, it is necessary to go through a specific development
