### ISSUE TITLE
Don't install

### ISSUE THREAD

**Issue by ti-ibg** [InfotelGLPI/resources#39]
Good Afternoon

 My version of the plugin 2.3.0
 My version of your GLPI 9.1.2

After downloading and able plugin in the GLPI and click in the link Human Resources

show the message

HTTP ERROR 500

And no create new menu in nowhere

![image](https://cloud.githubusercontent.com/assets/28407482/25721966/ba34c94a-30e8-11e7-9f3e-553892a7461e.png)

Can you Help me ?

**Comment by amma35** [comment]
Do you have any error logs when installing the plugin in glpi/_logs/php-errors.log and sql-errors.log ?

**Comment by amma35** [comment]
without answer, I close the issue for the moment
