### ISSUE TITLE
Title of information textarea in notification tab of a resource is not translated

### ISSUE THREAD

**Issue by tsmr** [InfotelGLPI/resources#4]
Version 2.1.0

In Notification tab of a resource, 'Information' textarea title is not translated. It always remains 'Information' whatever the language is.
In inc/reportconfig.class.php, line 264 seems to be wrong : echo "<td>".__('Information', 'Informations', 2)."</td>";
Have also a look at notificationtarget.class.php

**Comment by blerohellec** [comment]
Thx
