### ISSUE TITLE
Notifications problem

### ISSUE THREAD

**Issue by TarekDB7** [InfotelGLPI/resources#48]
Hi,

- In the installation of plugin, i can't found the different notifications.
- So, I configure the models of notifications and notifications manually in Configuration > Notifications.
- When i make actions ( for example : Leaving Resource ), no one notifications appear in my mail.

Version : GLPI 9.1.1 and GLPI 9.1.6 with PHP 5.4.
Plugin Version : 2.3.1 and 2.3.2.

Thanks for help.

**Comment by TarekDB7** [comment]
UPDATE

I'm trying with GLPI 9.2 with PHP 5.6 and the notification and notification templates are created in the plugin installation but the notifications still do not appear in my email.

**Comment by amma35** [comment]
Can you tell me how are the plugin notifications configured? (main interface, recipients, ..)

**Comment by TarekDB7** [comment]
That's to say ? I left the default notifications but for recipients people with the profile super-admin

**Comment by TarekDB7** [comment]
Anyone with a super administrator profile has an email address.

**Comment by TarekDB7** [comment]
amma35 what is your configuration ? This feature is OK on your side ?

**Comment by amma35** [comment]
Perform a test by putting as a recipient "Administrator" or a Group

**Comment by TarekDB7** [comment]
I test with a IT group but no one receive a mail, "Administrator" too.

**Comment by amma35** [comment]
The configuration of the notification looks like this:
![newresource](https://user-images.githubusercontent.com/15138371/32727706-d4f1337c-c87d-11e7-8535-b49ecaf8e13f.png)

A template is well linked to the notification?

You have no errors in log files glpi/files/_log/php-errors.log and sql-errors.log?

The notifications work well on my side.

**Comment by TarekDB7** [comment]
My notification is exactly like this.
I have a one word 'Test' in 36 lines in the file php-errors.log but i'm not sure it's about notifications.

**Comment by amma35** [comment]
it's not an entity problem?

**Comment by TarekDB7** [comment]
I just have one main entity. When i create a resource, it's always assigned to the main entity.

**Comment by amma35** [comment]
When creating the resource, the option "Send a notification" is activated?

**Comment by TarekDB7** [comment]
Yes

**Comment by TarekDB7** [comment]
I reinstall the plugin with GLPI 9.1.6 and PHP 5.6 and it works.
I notice that the notification elements are not configured from the first installation of the plugin.

**Comment by amma35** [comment]
I just retested with GLPI version 9.1.6 and 2.3.2 of the plugin.
There are 21 notifications created at installation.

**Comment by amma35** [comment]
Fix in [2.4.0](https://github.com/InfotelGLPI/resources/releases/tag/2.4.0)
