### ISSUE TITLE
Use Financial and administratives information

### ISSUE THREAD

**Issue by r0bertk** [InfotelGLPI/resources#50]
Hello, if there is an option Use Financial and administratives information in employees?

**Comment by amma35** [comment]
Hi, 
What information would you have liked? 
You mean the "Employee" part in the resource?

**Comment by r0bertk** [comment]
Actually, the topic can be closed, because I solved my problem by the field plugin in which I added missing fields to Human resources.
Another topic is I still need to mark a mandatory field in the wizard.  Is it possible?

**Comment by amma35** [comment]
The "Assignment rule of fields to a contract type" engine must be used
