### ISSUE TITLE
Impossible to create checklist

### ISSUE THREAD

**Issue by Zedhar** [InfotelGLPI/resources#53]
Bonjour,

Je viens d'installer la version 2.4.0 du plugin Resources sur GLPI 9.2.1 (Debian 9 - Nginx - PHP7 - MariaDB)

Il m'est impossible de créer une checklist. J'ai une page blanche.

Avez-vous une idée d'où cela peut venir svp ? Cela me le fait également sur une autre machine (GLPI 9.2.0 - Apache 2 - PHP5).

Merci d'avance pour votre retour.

Hello,

I just installed the 2.4.0 version of the Resources plugin on GLPI 9.2.1 (Debian 9 - Nginx - PHP7 - MariaDB)

I can not create a checklist. I have a blank page.

Do you have any idea where this may come from? It also does it on another machine (GLPI 9.2.0 - Apache 2 - PHP5)

Thank you in advance for your return.

**Comment by amma35** [comment]
Hi,

Do you have log errors in glpi/files/_log/php-errors. log and sql-errors. log files?

Can you put screenshots I can reproduce?

**Comment by Zedhar** [comment]
Hi,

There is also a problem on the schedule that does not take into account the tasks. Nothing is displayed. (the tasks of the plugin but also the basic tasks)

php-errors.log

```
2018-02-22 15:00:33 [303@---]
  *** PHP Notice(8): Undefined index: PluginResourcesTaskPlanning
  Backtrace :
  inc/planning.class.php:974                         
  inc/planning.class.php:1898                        Planning::getPaletteColor()
  ajax/planning.php:47                               Planning::constructEventsArray()
```

sql-errors.log
```  
Backtrace :
  plugins/dashboard/front/main.php:270               
2018-02-22 10:24:12 [2@---]
  *** MySQL query error:
  SQL: SELECT COUNT(glpi_tickets.id) as total        
      FROM glpi_tickets
      LEFT JOIN glpi_entities ON glpi_tickets.entities_id = glpi_entities.id
      WHERE glpi_tickets.is_deleted = '0' 
      AND DATE_FORMAT( glpi_tickets.date, '%Y' ) IN () 
      AND glpi_tickets.entities_id IN (0,2,1) 
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') 
      AND glpi_tickets.entities_id IN (0,2,1)' at line 5
  Backtrace :
  plugins/dashboard/front/main.php:270               
```

**Comment by amma35** [comment]
On the checklists page, can you switch to debug mode and put a screenshot again.

Then do you have errors during installation?

**Comment by Zedhar** [comment]
There is nothing in the page. When i clicked on the plus button to add the checklist, the page refresh one time but nothing is shown.
'<div id="page"><div style="background-image: url('/glpi/front/cron.php');"></div></div>'

In the network the URL given after clicked is.
'/glpi/plugins/resources/front/checklistconfig.form.php?new=1'

The header response give me a statut code 200.
I had no error during the installation.

I searched in the checklistconfig.form.php and i saw that there is no $_GET['new'] to get the parameter.

Is it normal ?

**Comment by amma35** [comment]
It's okay, I'm reproducing your bug, I didn't realize that you're trying to add an element.

**Comment by amma35** [comment]
To test can you reproduce the corrections here : https://github.com/InfotelGLPI/resources/commit/1a0bfb3dc99b20e7328e8131686dc7f43d623f28

**Comment by Zedhar** [comment]
It works ! Thanks.
