### ISSUE TITLE
Planning Issue

### ISSUE THREAD

**Issue by Zedhar** [InfotelGLPI/resources#54]
Hi,

As i said in my previous ticket, my planning isnt working (I can not see any notes or tasks).

It happens when the plugin is activated. 

My php-error log
`2018-02-22 15:00:33 [303@---]

  *** PHP Notice(8): Undefined index: PluginResourcesTaskPlanning
  Backtrace :
  inc/planning.class.php:974                         
  inc/planning.class.php:1898                        Planning::getPaletteColor()
  ajax/planning.php:47                               Planning::constructEventsArray()`

On the debug mode ive got this error
`there was an error while fetching events!`

Do you have any idea ?

Thanks by advance.

**Comment by tsmr** [comment]
Version of GLPI ?

**Comment by Zedhar** [comment]
Hi,

GLPI 9.2.1 (Debian 9 - Nginx - PHP7 - MariaDB)

**Comment by amma35** [comment]
Can you test with corrections to the "taskplanning. class. php" file?
