### ISSUE TITLE
Surname and Firstname in the drop-down list

### ISSUE THREAD

**Issue by r0bertk** [InfotelGLPI/resources#59]
hello, 
Is it possible to add a ticket so that Firstname also appears in the drop-down list with hardware type -> Human Resource?
![hr](https://user-images.githubusercontent.com/13787190/38522261-51b8e0c4-3c48-11e8-9637-308d7ceafe18.png)

Plugin Human Resources 2.4.3
GLPI 9.2.2

**Comment by amma35** [comment]
Hi,
Unfortunately, it is not possible to add the firstname without making any modification in the GLPI core.

**Comment by r0bertk** [comment]
Hi,
where can I send a request to perform this functionality on github glpi?
I need this option because we have employees with the same surname and we do not know when adding the ticket that is indicated

**Comment by amma35** [comment]
You can make a modification in the GLPI core if you want this modification? 
But you will have to make it with each update of GLPI except if a modification is eventually made in the core of GLPI to take into account the plugins to change the display of the drop-down list if you wish.

The modification to make in the heart if you wish: 
```
diff --git a/ajax/getDropdownFindNum.php b/ajax/getDropdownFindNum.php
index 37e1966f9..5e95040cc 100644
--- a/ajax/getDropdownFindNum.php
+++ b/ajax/getDropdownFindNum.php
@@ -141,6 +141,10 @@ if ($DB->numrows($result)) {
          $output = sprintf(__('%1$s - %2$s'), $output, $data['otherserial']);
       }
 
+      if ($item::getType() == 'PluginResourcesResource') {
+         $output = sprintf(__('%1$s %2$s'), $output, $data['firstname']);
+      }
+
```

**Comment by r0bertk** [comment]
Great thank you very much. It works :)

**Comment by FRANCOIS50** [comment]
Good Morning,
I installed GLPI 9.5.2 and Plugin Human Resources 2.7.0
It seems that the file ..../ajax/getDropdownFindNum.php is no more the same in GLPI 9.5.2 and your proposed change can not be executed to solve this problem. do you have an  idea wehre I can do it.
Thanks in advance for your help
regards
