### ISSUE TITLE
Sort of the needs list

### ISSUE THREAD

**Issue by FRANCOIS50** [InfotelGLPI/resources#61]
Hi,
is that possible that the needs list will be sorted according the name of the elements
It would be easier to check elements in the list

**Comment by FRANCOIS50** [comment]
Do you have an idea if it is possible?

**Comment by FRANCOIS50** [comment]
A small Up?

**Comment by amma35** [comment]
hi,
If you are talking about the checklist, we can't change the sorting on the name for the moment because this list is sorted according to the rank, i.e. according to the importance of the task.
This modification changes the whole of the current functioning.
