### ISSUE TITLE
Ticket resources associated element wrong dropdown list 

### ISSUE THREAD

**Issue by FRANCOIS50** [InfotelGLPI/resources#64]
GLPI 9.23
Plugin Resources 2.4.3
Hi in a ticket if I want to add a conneted element like human resources in the dropdown list only the name is displayed (no first name).
![2018-05-30_08h56_00](https://user-images.githubusercontent.com/12511115/40704152-e3d83c9c-63d6-11e8-8ef9-e92a0c622e2e.png)

If an human resource is added the cursor on the name display popup with the name + first name of the resource manager

![2018-05-30_08h57_56](https://user-images.githubusercontent.com/12511115/40704267-26dec772-63d7-11e8-9b4a-76f4f604fb4c.png)

Could you check this two problemes

**Comment by amma35** [comment]
No changes are possible in this subject.

Topic already discussed: https://github.com/InfotelGLPI/resources/issues/59

Idem for the second subject, it would be necessary modification in the heart of GLPI

**Comment by FRANCOIS50** [comment]
Thanks for your answer. I will add the change to my system.
