### ISSUE TITLE
Remove fields on create form

### ISSUE THREAD

**Issue by eddogniemad** [InfotelGLPI/resources#69]
Dear,
I want ot know if I'm able to remove some fiels on the create form of a new ressources. There is a lot of fields that I don't need and it will be very usefull to be able to remove them :)

Thanks,

------------
* Version of the plugin : 2.4.3

* Version of your GLPI : 9.2.2

**Comment by amma35** [comment]
Hi,
In the current state of the plugin, this is not possible.

Further development is needed to develop this functionality.

**Comment by eddogniemad** [comment]
Hi,
Thanks for your feedback !
