### ISSUE TITLE
Fields GRADES is not visible for normal users

### ISSUE THREAD

**Issue by KaminskiWojciech** [InfotelGLPI/resources#79]
Dear GLPi user.

BEFORE SUBMITTING YOUR ISSUE, please make sure to read and follow these steps :

* Verify that your question has not already been asked
* Please use the below template.
* Delete this text before submiting your issue.

The Plugin team.

------------
* Version of the plugin : 2.5.1

* Version of your GLPI : 9.3

* Steps to reproduce (which actions have you made) :
When I create the resource with field Grades ( I'm administrator) the others users can't see field GRADES. This field is not visible for normal users

* Expected result :
This fileds must be visible for others users

* Actual result :

* URL of the page :

* Screenshot of the problem (if pertinent) :

**Comment by keha35** [comment]
Hi,

You need to add "dropdown management" to the profile to see the field.
![image](https://user-images.githubusercontent.com/39367117/49389349-59ab0c00-f726-11e8-906a-cfa2a24e2e7b.png)

**Comment by KaminskiWojciech** [comment]
Thanks
