### ISSUE TITLE
Can't create Checklist / Select Contract

### ISSUE THREAD

**Issue by mo301080** [InfotelGLPI/resources#84]
Dear GLPi user.

BEFORE SUBMITTING YOUR ISSUE, please make sure to read and follow these steps :

* Verify that your question has not already been asked
* Please use the below template.
* Delete this text before submiting your issue.

The Plugin team.

------------
* Version of the plugin : 
2.6.1

* Version of your GLPI : 
9.4

* Steps to reproduce (which actions have you made) :
Go an "Declare an arrival", we can only select "without Contract". In the dropdown menu we have four entries. 
Also we can not create new checkliste.
* Expected result :
Select Contract and create Checkliste

* Screenshot of the problem (if pertinent) :
![image](https://user-images.githubusercontent.com/53090031/61544411-b2c17900-aa45-11e9-9dd6-3ffff208c1a4.png)
![image](https://user-images.githubusercontent.com/53090031/61544440-c2d95880-aa45-11e9-8804-a8f48f9a6dbc.png)
![image](https://user-images.githubusercontent.com/53090031/61544496-e6040800-aa45-11e9-9511-a9c8c7a8cc27.png)

**Comment by ales-infotel** [comment]
This select contract is not to select dropdown types of contract but to select a contract template, so you have to add new template.
![menu](https://user-images.githubusercontent.com/53440122/62451379-793f7c00-b76e-11e9-965d-a6946830b9bd.PNG)
![Capture](https://user-images.githubusercontent.com/53440122/62451388-7e043000-b76e-11e9-9379-33836d85b23c.PNG)

**Comment by mo301080** [comment]
Thank you for the information, but we can not create a checkliste. What I am doing wrong?
[2019-08-07 13-04-29.zip](https://github.com/InfotelGLPI/resources/files/3476653/2019-08-07.13-04-29.zip)

**Comment by keha35** [comment]
Hi,

For this issue, ales has create a fix that we juste merged.
We will release a new version of the plugin.
If you want to fix it now you can check wich files have been updated and apply the fix manualy.

Br.
