### ISSUE TITLE
Multiples errors on adding a new resource or Declaring an arrival

### ISSUE THREAD

**Issue by jcervantes-sipecom** [InfotelGLPI/resources#98]
* Version of the plugin : 
2.7.0
--

* Version of your GLPI : 
9.5.2
--

* Steps to reproduce (which actions have you made) :

1. Go to Administration
2. Clic on Human resources
3. Clic in the plus "+"-Add or in "Declare an arrival"
4. "To begin, select type of contract Without contract" Clic Next
5. See multiples errors.

* Expected result :
No errors on screen

* Actual result :
Multiples errors like:

```
- PHP Notice (8): Undefined index: security_display in /var/www/html/g952/plugins/resources/inc/config.class.php at line 194
- PHP Notice (8): Undefined index: security_compliance in /var/www/html/g952/plugins/resources/inc/config.class.php at line 201
- PHP Warning (2): Invalid argument supplied for foreach() in /var/www/html/g952/plugins/resources/inc/resource.class.php at line 2052
- PHP Warning (2): Invalid argument supplied for foreach() in /var/www/html/g952/plugins/resources/inc/resource.class.php at line 2096
- PHP Notice (8): Undefined index: security_display in /var/www/html/g952/plugins/resources/inc/config.class.php at line 194
```

* URL of the page :
/plugins/resources/front/wizard.form.php

* Screenshot of the problem (if pertinent) :
![image](https://user-images.githubusercontent.com/56606032/97644041-3888ee00-1a17-11eb-8f69-933c00c8911c.png)

**Comment by tsmr** [comment]
Hum.. This is a problem with install i think

**Comment by jcervantes-sipecom** [comment]
Ok, I will remove and clean the plugin, because these errors are in a previous version of the plugin too in 2.6.3 GLPI 9.4.6:

![image](https://user-images.githubusercontent.com/56606032/97712146-0f567500-1a8c-11eb-9cb9-c668645a77f2.png)

![image](https://user-images.githubusercontent.com/56606032/97712255-31e88e00-1a8c-11eb-9d26-b5e4fd7c0867.png)

I come back soon.

**Comment by jcervantes-sipecom** [comment]
Hi, @tsmr you were right, after remove and clean de plugin, and re-install it the errors disappear. Maybe it could be because I upgrade from GLPI 9.4.6 to 9.5.2, same with this plugin. 

And I checked it the same process with plugin 2.6.3 in GLPI 9.4.6 and these errors still are on this version:

- /plugins/resources/front/config.form.php

![image](https://user-images.githubusercontent.com/56606032/97722738-fbfdd680-1a98-11eb-981f-a2cef03c36f4.png)

- /plugins/resources/front/wizard.form.php

![image](https://user-images.githubusercontent.com/56606032/97722776-06b86b80-1a99-11eb-8fca-a13e80e95f2e.png)

**Comment by jcervantes-sipecom** [comment]
I found this error on the folder install in plugin version 2.6.3, in empty-2.6.3.sql on line 718 to 727 has:

```
DROP TABLE IF EXISTS `glpi_plugin_resources_configs`;
CREATE TABLE `glpi_plugin_resources_configs` (
   `id` int(11) NOT NULL auto_increment,
   `security_display` tinyint(1) NOT NULL default '0',
   `security_compliance` tinyint(1) NOT NULL default '0',
   `import_external_datas` tinyint(1) NOT NULL DEFAULT '0',
   `resource_manager` varchar(255) NOT NULL DEFAULT '',
   `sales_manager` varchar(255) NOT NULL DEFAULT '',
   PRIMARY KEY  (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
```

These has 6 fields, but in line 779:

>INSERT INTO `glpi_plugin_resources_configs` VALUES(1, 0, 0, 0);

Try to insert just 4 fields, when I do it manually in mysql I got this error:

```
INSERT INTO `glpi_plugin_resources_configs` VALUES(1, 0, 0, 0);
ERROR 1136 (21S01): Column count doesn't match value count at row 1
```

So if I manually do:

```
DROP TABLE IF EXISTS `glpi_plugin_resources_configs`;
CREATE TABLE `glpi_plugin_resources_configs` (
   `id` int(11) NOT NULL auto_increment,
   `security_display` tinyint(1) NOT NULL default '0',
   `security_compliance` tinyint(1) NOT NULL default '0',
   `import_external_datas` tinyint(1) NOT NULL DEFAULT '0',
   `resource_manager` varchar(255) NOT NULL DEFAULT '',
   `sales_manager` varchar(255) NOT NULL DEFAULT '',
   PRIMARY KEY  (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO `glpi_plugin_resources_configs` VALUES(1, 0, 0, 0, **'', ''**);
```

The errors dissapears:

![image](https://user-images.githubusercontent.com/56606032/97757422-ad693000-1aca-11eb-8d91-6ac740205a28.png)

![image](https://user-images.githubusercontent.com/56606032/97757445-b823c500-1aca-11eb-9b68-49fb6667644e.png)
